/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Frame;

import Controlador.CNTRL_LoginScreen;
import Controlador.CNTRL_MenuPrincipal;
import Modelo.Archivo.ArchivoUsuarios;
import java.util.Arrays;

/**
 *
 * @author sqdan
 */
public class FRM_LoginScreen extends javax.swing.JFrame {
    ArchivoUsuarios archivos;
    CNTRL_LoginScreen controlador;
    CNTRL_MenuPrincipal controladorMenu;
    
    /**
     * Creates new form LoginScreen
     */
    public FRM_LoginScreen(ArchivoUsuarios archivos, CNTRL_MenuPrincipal controladorMenu) {
        initComponents();
        this.archivos = archivos;
        this.controladorMenu = controladorMenu;
        controlador = new CNTRL_LoginScreen(this, archivos);
        agregarControlador();
    }
    
    public void copiarArchivo()
    {
        controlador.copiarArchivo();
    }
    
    public void mostrarMenu()
    {
        controladorMenu.mostrarMenu();
    }
    
    public void agregarControlador()
    {
        jbtn_Ingresar.addActionListener(controlador);
    }
    
    public String[] getLoginInfo()
    {
        String[] loginInfo = new String[2];
        
        loginInfo[0] = jtf_Usuario.getText();
        loginInfo[1] = (""+Arrays.toString(jpf_Pass.getPassword()));
        
        System.out.println("Login Info:\nUsuario: "+loginInfo[0]+"\nPass: "+loginInfo[1]);
        
        return loginInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Usuario = new javax.swing.JLabel();
        jl_Contraseña = new javax.swing.JLabel();
        jbtn_Ingresar = new javax.swing.JButton();
        jpf_Pass = new javax.swing.JPasswordField();
        jtf_Usuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_Usuario.setText("Usuario");

        jl_Contraseña.setText("Contraseña");

        jbtn_Ingresar.setText("Ingresar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_Contraseña)
                    .addComponent(jl_Usuario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_Ingresar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jpf_Pass, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addComponent(jtf_Usuario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Usuario)
                    .addComponent(jtf_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Contraseña)
                    .addComponent(jpf_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtn_Ingresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_Ingresar;
    private javax.swing.JLabel jl_Contraseña;
    private javax.swing.JLabel jl_Usuario;
    private javax.swing.JPasswordField jpf_Pass;
    private javax.swing.JTextField jtf_Usuario;
    // End of variables declaration//GEN-END:variables
}
