/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Frame;

import Controlador.CNTRL_MantenimientoUsuarios;
import Controlador.CNTRL_MenuPrincipal;

import Modelo.Archivo.ArchivoUsuarios;

/**
 *
 * @author sqdan
 */
public class FRM_MantenimientoUsuarios extends javax.swing.JFrame {
    CNTRL_MantenimientoUsuarios controlador;
    CNTRL_MenuPrincipal controlMenu;        
    ArchivoUsuarios archivos;
    String[] infoUsuario;
    public boolean firstRun = false;
    
    /**
     * Creates new form MantenimientoUsuarios
     */
    public FRM_MantenimientoUsuarios(ArchivoUsuarios archivos, CNTRL_MenuPrincipal controlPrincipal) 
    {
        initComponents();        
        controlador = new CNTRL_MantenimientoUsuarios(this, archivos);
        this.controlMenu = controlPrincipal;
        agregarControlador(controlador);
        infoUsuario = new String[4];
    }

    private void agregarControlador(CNTRL_MantenimientoUsuarios controlador)
    {
        pnl_UsuarioBotones.agregarControlador(controlador);
    }
    
    public String[] getInfo()
    {
        infoUsuario = pnl_UsuarioInfo.getInfo();
        
        return infoUsuario;
    }
    
    public void cargarArchivo()
    {
        controlador.cargarArchivo();
    }
    
    public void normalConfig()
    {
        firstRun = false;
        
        pnl_UsuarioBotones.primerUsuarioConfig();
    }
    
    public void primerUsuarioConfig()
    {
        firstRun = true;
        
        pnl_UsuarioBotones.primerUsuarioConfig();
    }
    
    public void finishFirstRun()
    {
        controlMenu.finishFirstRun();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_UsuarioInfo = new Vista.Panel.PNL_UsuarioInfo();
        pnl_UsuarioBotones = new Vista.Panel.PNL_UsuarioBotones();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_UsuarioInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_UsuarioBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_UsuarioInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_UsuarioBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.Panel.PNL_UsuarioBotones pnl_UsuarioBotones;
    private Vista.Panel.PNL_UsuarioInfo pnl_UsuarioInfo;
    // End of variables declaration//GEN-END:variables
}
