/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Frame;

import Controlador.CNTRL_MenuPrincipal;

import Modelo.Archivo.ArchivoUsuarios;

import javax.swing.JOptionPane;

/**
 *
 * @author sqdan
 */
public class FRM_MenuPrincipal extends javax.swing.JFrame {
    ArchivoUsuarios archivos;
    CNTRL_MenuPrincipal controlador;
    /**
     * Creates new form MenuPrincipal
     */
    public FRM_MenuPrincipal() {
        initComponents();
        archivos = new ArchivoUsuarios();        
        controlador = new CNTRL_MenuPrincipal(this, archivos);
        agregarControlador(controlador);
        setResizable(false);
        ordenarVentanas();
    }

    public void ordenarVentanas()
    {
        if(archivos.cargarArchivo())
        {
            controlador.mostrarVentanaLogin();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No hay ningún usuario registrado en el sistema.\nDebe crear un nuevo usuario antes de continuar.");
            controlador.crearPrimerUsuario();
        }
    }
    
    public void agregarControlador(CNTRL_MenuPrincipal controlador)
    {
        jmi_Usuarios.addActionListener(controlador);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmb_Archivo = new javax.swing.JMenu();
        jmi_Salir = new javax.swing.JMenuItem();
        jmb_Editar = new javax.swing.JMenu();
        jmi_Usuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N

        jmb_Archivo.setText("Archivo");

        jmi_Salir.setText("Salir");
        jmb_Archivo.add(jmi_Salir);

        jMenuBar1.add(jmb_Archivo);

        jmb_Editar.setText("Editar");

        jmi_Usuarios.setText("Usuarios");
        jmb_Editar.add(jmi_Usuarios);

        jMenuBar1.add(jmb_Editar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jl_Fondo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jl_Fondo)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_MenuPrincipal().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jl_Fondo;
    private javax.swing.JMenu jmb_Archivo;
    private javax.swing.JMenu jmb_Editar;
    private javax.swing.JMenuItem jmi_Salir;
    private javax.swing.JMenuItem jmi_Usuarios;
    // End of variables declaration//GEN-END:variables
}
