/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Panel;

import java.util.Arrays;

/**
 *
 * @author sqdan
 */
public class PNL_UsuarioInfo extends javax.swing.JPanel {

    /**
     * Creates new form PNL_UsuarioInfo
     */
    public PNL_UsuarioInfo() {
        initComponents();
    }
    
        
    public String[] getInfo()
    {
        String[] infoUsuario = new String[4];
        
        infoUsuario[0] = jtf_Nombre.getText();
        infoUsuario[1] = jtf_Usuario.getText();
        infoUsuario[2] = (""+Arrays.toString(jpf_Pass.getPassword()));
        infoUsuario[3] = jtf_Tipo.getText();
        
        return infoUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jl_Usuario = new javax.swing.JLabel();
        jl_Contraseña = new javax.swing.JLabel();
        jl_Tipo = new javax.swing.JLabel();
        jtf_Usuario = new javax.swing.JTextField();
        jtf_Nombre = new javax.swing.JTextField();
        jtf_Tipo = new javax.swing.JTextField();
        jpf_Pass = new javax.swing.JPasswordField();

        jLabel1.setText("jLabel1");

        jl_Nombre.setText("Nombre");

        jl_Usuario.setText("Usuario");

        jl_Contraseña.setText("Contraseña");

        jl_Tipo.setText("Tipo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_Contraseña)
                    .addComponent(jl_Usuario)
                    .addComponent(jl_Nombre)
                    .addComponent(jl_Tipo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jtf_Usuario)
                    .addComponent(jtf_Tipo)
                    .addComponent(jpf_Pass))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Nombre)
                    .addComponent(jtf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Usuario)
                    .addComponent(jtf_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Contraseña)
                    .addComponent(jpf_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Tipo)
                    .addComponent(jtf_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jl_Contraseña;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_Tipo;
    private javax.swing.JLabel jl_Usuario;
    private javax.swing.JPasswordField jpf_Pass;
    private javax.swing.JTextField jtf_Nombre;
    private javax.swing.JTextField jtf_Tipo;
    private javax.swing.JTextField jtf_Usuario;
    // End of variables declaration//GEN-END:variables
}
